default: default
enablemanagers: false
enablechatman: false
chatman: "&7%x%p&7%s&8: &7%m"
usevault: false

mysql:
  enabled: false
  ip: "yourip.tld"
  port: 3306
  database: "walrus_database"
  username: "seagull_username"
  password: "your_secret_password"