default: default
chatmanager: false
chatman: "&7%x%p&7%s&8: &7%m"
tabmanager: false
usevault: false
antibuild: false
mysql:
  enabled: false
  ip: "yourip.tld"
  port: 3306
  database: "walrus_database"
  username: "seagull_username"
  password: "your_secret_password"