name: KevsPermissions
version: 1.7-pre4
author: Kev575
main: kev575.permissions.KevsPermissions
description: A lightweight permissions plugin every serveradmin must have! With Yaml! Thank you for 500 downloads on SpigotMC.org!
commands:
  kevspermissions:
    aliases: [kp]