name: KevsPermissions
version: 1.5d
author: Kev575
main: kev575.permissions.KevsPermissions
description: A lightweight permissions plugin every serveradmin must have! With MySQL and Json!
commands:
  kevspermissions:
    aliases: [kp]