name: KevsPermissions
version: 1.3b
author: Kev575
main: kev575.permissions.KevsPermissions
description: A lightweight permissions plugin every serveradmin must have!
commands:
  kevspermissions:
    aliases: [kp]