name: KevsPermissions
version: 1.7-pre1
author: Kev575
main: kev575.permissions.KevsPermissions
description: A lightweight permissions plugin every serveradmin must have! With Yaml!
commands:
  kevspermissions:
    aliases: [kp]